export default {
    api1: '/api/v1/banner',
    api2: '/api/v1/auth/token',
    api3: '/api/v1/user/token',
    api4: '/api/v1/user/me',
    api5: '/api/v1/user/token/revoke',
    // api6: '/api/v1/user/buff',
    api7: '/api/v1/sign_in/count',
    api8: '/api/v1/mission',
    api9: '/api/v1/mission/trigger',
    api10: '/api/v1/sign_in/check',
    api11: '​/api​/v1​/member​/active​/code​/register',
    api12: '/api/v1/member',
    api13: '/api/v1/member/getFirstMember',
    api14: '/api/v1/member/inviter',
    api15: '/api/v1/game',
    api16: '/api/v1/game/get/',
    api17: '/api/v1/ucoin/map',
    api18: '/api/v1/ucoin/currency',
    api19: '/api/v1/ucoin/trade',
    api20: '/api/v1/qrcode'
}